# Generated by Django 6.0.1 on 2026-02-01 11:09

import analyzer.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Paper title extracted from filename or content', max_length=500)),
                ('pdf_file', models.FileField(help_text='Uploaded PDF file', upload_to=analyzer.models.upload_paper_to)),
                ('original_filename', models.CharField(help_text='Original filename of uploaded PDF', max_length=255)),
                ('abstract', models.TextField(blank=True, help_text='Paper abstract')),
                ('motivation', models.TextField(blank=True, help_text='Research motivation')),
                ('contribution', models.TextField(blank=True, help_text='Key contributions')),
                ('what_does_paper_do', models.TextField(blank=True, help_text='Experiments and results')),
                ('how_does_paper_do', models.TextField(blank=True, help_text='Methodology and framework')),
                ('limitations_challenges', models.TextField(blank=True, help_text='Limitations and challenges')),
                ('future_work', models.TextField(blank=True, help_text='Future work suggestions')),
                ('conclusion', models.TextField(blank=True, help_text='Conclusion')),
                ('analysis_data', models.JSONField(blank=True, default=dict, help_text='Complete analysis as JSON')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='When the analysis was created')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='When the analysis was last updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paper Analysis',
                'verbose_name_plural': 'Paper Analyses',
                'ordering': ['-created_date'],
            },
        ),
    ]
