# Generated by Django 6.0.1 on 2026-02-01 11:18

import analyzer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperanalysis',
            name='pdf_file',
            field=models.FileField(help_text='Uploaded PDF file', max_length=500, upload_to=analyzer.models.upload_paper_to),
        ),
    ]
