# Generated by Django 6.0.1 on 2026-02-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_paperanalysis_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperanalysis',
            name='authors',
            field=models.TextField(blank=True, help_text='Paper authors (comma-separated)'),
        ),
        migrations.AddField(
            model_name='paperanalysis',
            name='introduction',
            field=models.TextField(blank=True, help_text='Introduction and related work'),
        ),
        migrations.AddField(
            model_name='paperanalysis',
            name='paper_url',
            field=models.URLField(blank=True, help_text='Paper download URL'),
        ),
        migrations.AddField(
            model_name='paperanalysis',
            name='student_id',
            field=models.CharField(blank=True, help_text='Student ID for presentation', max_length=50),
        ),
        migrations.AddField(
            model_name='paperanalysis',
            name='student_name',
            field=models.CharField(blank=True, help_text='Student name for presentation', max_length=255),
        ),
        migrations.AddField(
            model_name='paperanalysis',
            name='venue',
            field=models.CharField(blank=True, help_text='Publication venue (journal/conference)', max_length=255),
        ),
        migrations.AddField(
            model_name='paperanalysis',
            name='year',
            field=models.CharField(blank=True, help_text='Publication year', max_length=10),
        ),
    ]
