# Generated by Django 6.0.1 on 2026-02-09 12:59

import analyzer.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_paperanalysis_authors_paperanalysis_introduction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperanalysis',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='paperanalysis',
            name='student_name',
        ),
        migrations.CreateModel(
            name='PPTGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Paper title extracted from filename or content', max_length=500)),
                ('pdf_file', models.FileField(help_text='Uploaded PDF file', max_length=500, upload_to=analyzer.models.upload_ppt_paper_to)),
                ('original_filename', models.CharField(help_text='Original filename of uploaded PDF', max_length=255)),
                ('authors', models.TextField(blank=True, help_text='Paper authors (comma-separated)')),
                ('venue', models.CharField(blank=True, help_text='Publication venue (journal/conference)', max_length=255)),
                ('year', models.CharField(blank=True, help_text='Publication year', max_length=10)),
                ('paper_url', models.URLField(blank=True, help_text='Paper download URL')),
                ('student_name', models.CharField(blank=True, help_text='Student name for presentation', max_length=255)),
                ('student_id', models.CharField(blank=True, help_text='Student ID for presentation', max_length=50)),
                ('abstract', models.TextField(blank=True, help_text='Paper abstract for speaker notes')),
                ('introduction', models.TextField(blank=True, help_text='Introduction and related work (slide-ready)')),
                ('motivation', models.TextField(blank=True, help_text='Research motivation (slide-ready)')),
                ('contribution', models.TextField(blank=True, help_text='Key contributions (slide-ready)')),
                ('what_does_paper_do', models.TextField(blank=True, help_text='Experiments and results (slide-ready)')),
                ('how_does_paper_do', models.TextField(blank=True, help_text='Methodology and framework (slide-ready)')),
                ('future_work', models.TextField(blank=True, help_text='Future work suggestions (slide-ready)')),
                ('conclusion', models.TextField(blank=True, help_text='Conclusion (slide-ready)')),
                ('analysis_data', models.JSONField(blank=True, default=dict, help_text='Complete PPT-optimized analysis as JSON')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='When the PPT was generated')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='When the record was last updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppt_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PPT Generation',
                'verbose_name_plural': 'PPT Generations',
                'ordering': ['-created_date'],
            },
        ),
    ]
